from datetime import datetime, timedelta
from database import init_db, get_conn


def seed_vehicles() -> None:
    init_db()

    vehicles = [
        {
            "vin": "JTHBP5C2XA5034186",
            "license_plate": "SGB1234A",
            "make": "Toyota",
            "model": "Camry",
            "year": 2022,
            "mileage": 42000,
            "purchase_price": 98000,
            "arf": 45000,
            "coe": 65000,
            "coe_at_purchase": 65000,
            "current_coe": 68000,
            "registration_date": "2022-03-15",
            "date_acquired": (datetime.utcnow() - timedelta(days=45)).date().isoformat(),
            "entry_date": (datetime.utcnow() - timedelta(days=45)).date().isoformat(),
            "estimated_value": 95000,
            "current_market_value": 95000,
            "recommended_intake_price": 90000,
            "target_selling_price": 103000,
            "depreciation_rate": 0.08,
            "profit_margin": 0.03,
            "risk_level": "MEDIUM",
            "recommendation": "MONITOR",
            "recommendation_reason": "Vehicle is moving but margin is thin.",
            "sold_price": 0,
            "sold_date": "",
            "vehicle_type": "Sedan",
            "seat_count": 5,
            "days_in_inventory": 45,
            "status": "AVAILABLE",
        },
        {
            "vin": "WBADT43452G297186",
            "license_plate": "SFD5678B",
            "make": "BMW",
            "model": "3 Series",
            "year": 2020,
            "mileage": 78000,
            "purchase_price": 132000,
            "arf": 55000,
            "coe": 75000,
            "coe_at_purchase": 75000,
            "current_coe": 77000,
            "registration_date": "2020-06-20",
            "date_acquired": (datetime.utcnow() - timedelta(days=120)).date().isoformat(),
            "entry_date": (datetime.utcnow() - timedelta(days=120)).date().isoformat(),
            "estimated_value": 85000,
            "current_market_value": 85000,
            "recommended_intake_price": 78000,
            "target_selling_price": 93000,
            "depreciation_rate": 0.12,
            "profit_margin": -0.36,
            "risk_level": "HIGH",
            "recommendation": "SELL SOON",
            "recommendation_reason": "Age and depreciation are both high.",
            "sold_price": 0,
            "sold_date": "",
            "vehicle_type": "Sedan",
            "seat_count": 5,
            "days_in_inventory": 120,
            "status": "AVAILABLE",
        },
        {
            "vin": "JH2RC5004LM100186",
            "license_plate": "SGH2135C",
            "make": "Honda",
            "model": "Civic",
            "year": 2023,
            "mileage": 18000,
            "purchase_price": 67000,
            "arf": 35000,
            "coe": 55000,
            "coe_at_purchase": 55000,
            "current_coe": 56000,
            "registration_date": "2023-01-10",
            "date_acquired": (datetime.utcnow() - timedelta(days=8)).date().isoformat(),
            "entry_date": (datetime.utcnow() - timedelta(days=8)).date().isoformat(),
            "estimated_value": 78000,
            "current_market_value": 78000,
            "recommended_intake_price": 76000,
            "target_selling_price": 85000,
            "depreciation_rate": 0.05,
            "profit_margin": 0.16,
            "risk_level": "LOW",
            "recommendation": "HOLD INVENTORY",
            "recommendation_reason": "Good profit margin and recent stock.",
            "sold_price": 0,
            "sold_date": "",
            "vehicle_type": "Hatchback",
            "seat_count": 5,
            "days_in_inventory": 8,
            "status": "AVAILABLE",
        },
        {
            "vin": "LVVFA21D872186",
            "license_plate": "SGP8421D",
            "make": "Volvo",
            "model": "XC90",
            "year": 2019,
            "mileage": 112000,
            "purchase_price": 125000,
            "arf": 50000,
            "coe": 70000,
            "coe_at_purchase": 70000,
            "current_coe": 74000,
            "registration_date": "2019-09-05",
            "date_acquired": (datetime.utcnow() - timedelta(days=90)).date().isoformat(),
            "entry_date": (datetime.utcnow() - timedelta(days=90)).date().isoformat(),
            "estimated_value": 92000,
            "current_market_value": 92000,
            "recommended_intake_price": 86000,
            "target_selling_price": 99000,
            "depreciation_rate": 0.1,
            "profit_margin": -0.26,
            "risk_level": "HIGH",
            "recommendation": "SELL SOON",
            "recommendation_reason": "Inventory age is high and margin is negative.",
            "sold_price": 0,
            "sold_date": "",
            "vehicle_type": "SUV",
            "seat_count": 7,
            "days_in_inventory": 90,
            "status": "RESERVED",
        },
        {
            "vin": "1HGBH41JXMN109186",
            "license_plate": "SGX5050E",
            "make": "Acura",
            "model": "TL",
            "year": 2021,
            "mileage": 54000,
            "purchase_price": 84000,
            "arf": 42000,
            "coe": 62000,
            "coe_at_purchase": 62000,
            "current_coe": 64000,
            "registration_date": "2021-11-12",
            "date_acquired": (datetime.utcnow() - timedelta(days=25)).date().isoformat(),
            "entry_date": (datetime.utcnow() - timedelta(days=25)).date().isoformat(),
            "estimated_value": 88000,
            "current_market_value": 88000,
            "recommended_intake_price": 84000,
            "target_selling_price": 94000,
            "depreciation_rate": 0.07,
            "profit_margin": 0.05,
            "risk_level": "MEDIUM",
            "recommendation": "MONITOR",
            "recommendation_reason": "Margin is modest and should be tracked.",
            "sold_price": 0,
            "sold_date": "",
            "vehicle_type": "Sedan",
            "seat_count": 5,
            "days_in_inventory": 25,
            "status": "AVAILABLE",
        },
        {
            "vin": "KMHLN4AJ5FU186186",
            "license_plate": "SGY0901F",
            "make": "Hyundai",
            "model": "Sonata",
            "year": 2018,
            "mileage": 98000,
            "purchase_price": 76000,
            "arf": 38000,
            "coe": 58000,
            "coe_at_purchase": 58000,
            "current_coe": 61000,
            "registration_date": "2018-05-22",
            "date_acquired": (datetime.utcnow() - timedelta(days=180)).date().isoformat(),
            "entry_date": (datetime.utcnow() - timedelta(days=180)).date().isoformat(),
            "estimated_value": 68000,
            "current_market_value": 68000,
            "recommended_intake_price": 64000,
            "target_selling_price": 72000,
            "depreciation_rate": 0.15,
            "profit_margin": -0.11,
            "risk_level": "HIGH",
            "recommendation": "SELL SOON",
            "recommendation_reason": "Old stock with negative profit margin.",
            "sold_price": 0,
            "sold_date": "",
            "vehicle_type": "Sedan",
            "seat_count": 5,
            "days_in_inventory": 180,
            "status": "AVAILABLE",
        },
        {
            "vin": "WVWZZZ3CZ9E186186",
            "license_plate": "SGM4457G",
            "make": "Volkswagen",
            "model": "Passat",
            "year": 2022,
            "mileage": 33000,
            "purchase_price": 88000,
            "arf": 40000,
            "coe": 60000,
            "coe_at_purchase": 60000,
            "current_coe": 62000,
            "registration_date": "2022-08-18",
            "date_acquired": (datetime.utcnow() - timedelta(days=35)).date().isoformat(),
            "entry_date": (datetime.utcnow() - timedelta(days=35)).date().isoformat(),
            "estimated_value": 92000,
            "current_market_value": 92000,
            "recommended_intake_price": 88000,
            "target_selling_price": 99000,
            "depreciation_rate": 0.06,
            "profit_margin": 0.05,
            "risk_level": "MEDIUM",
            "recommendation": "MONITOR",
            "recommendation_reason": "Low depreciation but modest margin.",
            "sold_price": 0,
            "sold_date": "",
            "vehicle_type": "Sedan",
            "seat_count": 5,
            "days_in_inventory": 35,
            "status": "AVAILABLE",
        },
        {
            "vin": "JT2BF28K1M0186186",
            "license_plate": "SGC2278H",
            "make": "Toyota",
            "model": "Mark X",
            "year": 2017,
            "mileage": 125000,
            "purchase_price": 82000,
            "arf": 36000,
            "coe": 56000,
            "coe_at_purchase": 56000,
            "current_coe": 59000,
            "registration_date": "2017-02-14",
            "date_acquired": (datetime.utcnow() - timedelta(days=160)).date().isoformat(),
            "entry_date": (datetime.utcnow() - timedelta(days=160)).date().isoformat(),
            "estimated_value": 64000,
            "current_market_value": 64000,
            "recommended_intake_price": 61000,
            "target_selling_price": 69000,
            "depreciation_rate": 0.14,
            "profit_margin": -0.22,
            "risk_level": "HIGH",
            "recommendation": "SELL SOON",
            "recommendation_reason": "High age, depreciation, and low margin.",
            "sold_price": 0,
            "sold_date": "",
            "vehicle_type": "Sedan",
            "seat_count": 5,
            "days_in_inventory": 160,
            "status": "RESERVED",
        },
    ]

    with get_conn() as conn:
        for vehicle in vehicles:
            conn.execute(
                """
                INSERT OR REPLACE INTO vehicles 
                (vin, license_plate, make, model, year, mileage, purchase_price, arf, coe, coe_at_purchase, current_coe,
                 registration_date, date_acquired, entry_date, estimated_value, current_market_value,
                 recommended_intake_price, target_selling_price, depreciation_rate, profit_margin,
                 risk_level, recommendation, recommendation_reason, sold_price, sold_date, vehicle_type,
                 seat_count, days_in_inventory, status)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    vehicle["vin"],
                    vehicle["license_plate"],
                    vehicle["make"],
                    vehicle["model"],
                    vehicle["year"],
                    vehicle["mileage"],
                    vehicle["purchase_price"],
                    vehicle["arf"],
                    vehicle["coe"],
                    vehicle["coe_at_purchase"],
                    vehicle["current_coe"],
                    vehicle["registration_date"],
                    vehicle["date_acquired"],
                    vehicle["entry_date"],
                    vehicle["estimated_value"],
                    vehicle["current_market_value"],
                    vehicle["recommended_intake_price"],
                    vehicle["target_selling_price"],
                    vehicle["depreciation_rate"],
                    vehicle["profit_margin"],
                    vehicle["risk_level"],
                    vehicle["recommendation"],
                    vehicle["recommendation_reason"],
                    vehicle.get("sold_price", 0),
                    vehicle.get("sold_date", ""),
                    vehicle.get("vehicle_type", ""),
                    vehicle.get("seat_count", 5),
                    vehicle["days_in_inventory"],
                    vehicle["status"],
                ),
            )

    print("Inventory seed completed: 8 vehicles created.")


if __name__ == "__main__":
    seed_vehicles()
